import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': 'Login',
          'payment_successful': 'Payment Successful',
          'cancelled': 'Cancelled',
          'equipments': 'Equipments',
          'about': 'About',
          'privacy_policy': 'PRIVACY POLICY',
          'complete_your_profile': 'Complete your\nProfile',
          'full_name': 'Full name',
          'email_address': 'Email address',
          'phone_no': 'Phone no',
          'confirm_booking': 'Confirm Booking',
          'starting_date': 'Starting Date:',
          'ending_date': 'Ending Date:',
          'timing': 'Time:',
          'days': 'Days:',
          'gym': 'Gym:',
          'location': 'Location:',
          'charges': 'Charges:',
          'note': 'Note:',
          'you_will_be_charged': '\"You will be charged if you cancel the booking less than 16 hours prior\"',
          'continue_to_payment': 'Continue to payment',
          'here_you_find_best_trainers_and_equipments': 'Here you can find best equipments we could offer',
          'opening_time': 'Opening Time: ',
          'closing_time': 'Closing Time: ',
          'night': '(Night)',
          'next_level_equipments': 'Equipments on site',
          'select_date_and_time': 'Select Date And Time',
          'book_now': 'Book Now',
          'signin_with': 'Sign In with',
          'booking_details': 'Booking Details',
          'date': 'Date:',
          'cancellation_pending': 'Cancellation Pending',
          'cancel_booking': 'Cancel Booking',
          'are_you_really_want_ancel': 'Confirm cancellation?',
          'yes': 'Yes',
          'cancellation_request_submitted': 'Cancellation request submitted.',
          'settings': 'Settings',
          'notifications': 'Notifications',
          'first_reminder': 'First reminder',
          'second_reminder': 'Second reminder',
          'no_new_notifications': 'No New\nNotifications',
          'clear': 'Clear',
          'enter_your': 'Enter your\n',
          'one_time_pin': 'One Time Pin',
          'enter_the_code': 'Enter the code',
          'we_sent_you_message_with_otp': 'We sent you a message with an OTP to your registered number',
          'resend_code': 'Resend Code',
          'resend_in': 'Resend in',
          'payment': 'Payment',
          'credit_card': 'Credit/Debit Card',
          'paypal': 'Paypal',
          'proceed_payment': 'Proceed Payment',
          'are_you_really_want_proceed': 'Are you really want to proceed?',
          'you_have_successfully_purchased': 'You have successfully purchased.',
          'update_profile': 'Update Profile',
          'update': 'Update',
          'profile_details_updated': 'Profile details updated.',
          'stay_healthy_fit': 'Stay Healthy & Fit',
          'get_perfect_body': 'Mens sana in corpore sano',
          'i_believe_in_training_with_intensity': 'Everybody wants to be fit',
          'upcoming_session': 'Upcoming Session',
          'today_at': 'Today at',
          'nearest_gym_from_your_location': 'Nearest Gym From Your Location',
          'favorite_locations': 'Favorite Locations',
          'choose_gym_that_suits_you': 'Choose a Gym That Suits you The Most',
          'my_bookings': 'My Bookings',
          'no_bookings': 'No Bookings',
          'feedback': 'Feedback',
          'contact_us': 'Contact us',
          'logout_from_alphaFit': 'Logout from AlphaFit',
          'logout': 'Logout',
          'cleanings': 'Cleanings',
          'today': 'Today',
          'recurring': 'Recurring',
          'continue': 'Continue',
          'select_recurring': 'Select Recurring',
          'total': 'Total',
          'months': 'Months',
          'years': 'Years',
          'start_date': 'Start Date',
          'time': 'Time',
          'additional_info': 'Additional Information (if any)',
          'tell_us_if': 'Tell us if you have any suggestions',
          'booking_days': 'Booking Days',
          'single': 'Single',
          'gym_name': 'Gym name',
          'claimed': 'Claimed',
          'claim': 'Claim',
          'at': '',
          'distance_from_your_current_loc': ' From Your Current Location!',
          'view_details': 'View Details',
          'home': 'Home',
          'booking': 'Booking',
          'profile': 'Profile',
          'single_booking': 'Single Booking',
          'recurring_bookings': 'Recurring Bookings',
          'success': 'Success',
          'ok': 'OK',
          'confrim': 'Confirm',
          'cancel': 'Cancel',
          'no': 'NO',
          'change_lang': 'Change language',
          'choose_lang': 'Choose language',
          'quote_1': '\"Alphafit Shape it up!\"',
          'quote_2': '\"Alphafit Be part of the Elite\"',
          'quote_3': '',
          'uploading': 'Uploading...',
          'loading': 'Loading...',
          'uploaded_successfully': 'Uploaded successfully!',
          'no_directions_found': 'No directions found',
          'no_slots_available_for': 'No slots available for',
          'tap_to_book': 'Tap to book',
          'gyms': 'Gyms',
          'delete': 'Delete',
          'are_you_really_want_to_delete': 'Are you sure to delete',
          'blocked': 'Blocked',
          'contact_to_the_admin': 'Contact to the administrator',
        
        },
        'fr_FR': {
          'login': 'Connexion',
          'payment_successful': 'Paiement effectué',
          'cancelled': 'Annulé',
          'equipments': 'Équipements',
          'about': 'À propos',
          'privacy_policy': 'Politique de confidentialité',
          'complete_your_profile': 'Complétez votre profil',
          'full_name': 'Nom complet',
          'email_address': 'Addresse courriel',
          'phone_no': 'Num de téléphone',
          'confirm_booking': 'Confirmer réservation',
          'starting_date': 'Date de début:',
          'ending_date': 'Date de fin:',
          'timing': 'Heure:',
          'days': 'Jour:',
          'gym': 'Gym:',
          'location': 'Endroit:',
          'charges': 'Charges:',
          'note': 'Note:',
          'you_will_be_charged': '\"Vous serez chargé si vous annulez la reservation moins de 16 heures avant.\"',
          'continue_to_payment': 'Continuer vers le paiement',
          'here_you_find_best_trainers_and_equipments': 'Ici vous trouverez les meilleurs equipements qu\'on a pu vous offrir',
          'opening_time': "Heure d\'ouverture: ",
          'closing_time': 'Heure de fermeture: ',
          'night': '(Nuit)',
          'next_level_equipments': 'Equipements à la pointe',
          'select_date_and_time': 'Choisir Date et Heure',
          'book_now': 'Réservez maintenant',
          'signin_with': 'Connectez vous avec',
          'booking_details': 'Details de réservation',
          'date': 'Date:',
          'cancellation_pending': 'Annulation en cours',
          'cancel_booking': 'Annuler réservation',
          'are_you_really_want_ancel': 'Voulez-vous vraiment annuler?',
          'yes': 'Oui',
          'cancellation_request_submitted': 'Demande d\'annulation soumise.',
          'settings': 'Paramètres',
          'notifications': 'Notifications',
          'first_reminder': 'Premier rappel',
          'second_reminder': 'Deuxiéme rappel',
          'no_new_notifications': 'Aucune nouvelle notification',
          'clear': 'Effacer',
          'enter_your': 'Entrez votre\n',
          'one_time_pin': 'Mot de passe unique',
          'enter_the_code': 'Entrez le code',
          'we_sent_you_message_with_otp': 'Nous vous avons envoyez un message avec un mot de passe unique sur le numero à votre dossier',
          'resend_code': 'Renvoyer code',
          'resend_in': 'Renvoyer dans',
          'payment': 'Paiment',
          'credit_card': 'Carte de Crédit/Débito',
          'paypal': 'Paypal',
          'proceed_payment': 'Procéder au paiement',
          'are_you_really_want_proceed': 'Voulez vous vraiment procéder?',
          'you_have_successfully_purchased': 'Achat réussi.',
          'update_profile': 'Mettre à jour profil',
          'update': 'Mettre à jour',
          'profile_details_updated': 'Profil mis à jour.',
          'stay_healthy_fit': 'Restez en santé et en forme',
          'get_perfect_body': 'Mens sana in corpore sano',
          'i_believe_in_training_with_intensity': 'Tout le monde veut être en shape!',
          'upcoming_session': 'Session à venir',
          'today_at': 'Aujourd\'hui à',
          'nearest_gym_from_your_location': 'Salle la plus proche de votre localisation',
          'favorite_locations': 'Salles favorites',
          'choose_gym_that_suits_you': 'Choisissez le gym qui vous convient le mieux',
          'my_bookings': 'Mes réservations',
          'no_bookings': 'Aucune réservation',
          'feedback': 'Feedback',
          'contact_us': 'Contactez nous',
          'logout_from_alphaFit': 'Se déconnecter',
          'logout': 'Se déconnecter',
          'cleanings': 'Nettoyages',
          'today': 'Aujourd\'hui',
          'recurring': 'Récurrent',
          'continue': 'Continuer',
          'select_recurring': 'Choisir récurrence',
          'total': 'Total',
          'months': 'Mois',
          'years': 'Années',
          'start_date': 'Date de début',
          'time': 'Heure',
          'additional_info': 'Information additionnelle (si applicable)',
          'tell_us_if': 'Laissez nous savoir votre avis',
          'booking_days': 'Jours réservés',
          'single': 'Single',
          'gym_name': 'Nom de salle',
          'claimed': 'Claimed',
          'claim': 'Claim',
          'at': 'A ',
          'distance_from_your_current_loc': ' Distance de votre localisation!',
          'view_details': 'Voir Details',
          'home': 'Home',
          'booking': 'Réservation',
          'profile': 'Profil',
          'single_booking': 'Réservation unique',
          'recurring_bookings': 'Réservation récurrente',
          'success': 'Succès',
          'ok': 'D\'accord',
          'confrim': 'Confirmer',
          'cancel': 'Annuler',
          'no': 'NON',
          'change_lang': 'Changer de langue',
          'choose_lang': 'Choisissez la langue',
          'quote_1': '\"Alphafit Mettez-le en forme!\"',
          'quote_2': '\"Alphafit Faites partie de l\'élite\"',
          'quote_3': '',
          'uploading': 'Téléchargement...',
          'loading': 'Chargement...',
          'uploaded_successfully': 'Téléchargé avec succès!',
          'no_directions_found': 'Aucun itinéraire trouvé',
          'no_slots_available_for': 'Aucun créneau disponible pour',
          'tap_to_book': 'Réserver',
          'gyms': 'Gymnases',
          'delete': 'Effacer',
          'are_you_really_want_to_delete': 'Êtes-vous sûr de vouloir supprimer',
            'blocked': 'Obstruido',
          'contact_to_the_admin': 'Contacto con el administrador',
        }
      };
}
